### ISSUE TITLE
Triage: click 8.4 made ParamType generic — bare ParamType subclass in ctl/_group.py fails mypy [type-arg]

### ISSUE THREAD

**Issue by i-am-marvin** [meridianlabs-ai/inspect_ai#306]
## Summary

`click` **8.4.2** (resolved for the first time in this run) made `click.ParamType` a real `Generic`, so the bare `click.ParamType` base at `src/inspect_ai/_cli/ctl/_group.py:28` now trips `disallow_any_generics` and fails `static-analysis` with a single mypy error. Runtime is unaffected (both `slow-tests` legs are green); this is a typing-only break and it will **not** clear on the next scheduled run.

## Failing tests

`static-analysis` → `Run mypy` (`mypy --exclude tests/test_package src tests`) — 1 error:

```
src/inspect_ai/_cli/ctl/_group.py:28: error: Missing type arguments for generic type "ParamType"  [type-arg]
Found 1 error in 1 file (checked 1389 source files)
```

No test failures: `slow-tests (asyncio, 900)` and `slow-tests (trio, --runtrio, 1500)` both passed.

## Root cause

`requirements.txt:6` pins `click>=8.1.3,!=8.2.0,!=8.2.2,!=8.3.0,!=8.3.1`, and the install log for the failed `static-analysis` job shows pip resolving **click 8.4.2** (alongside `inspect-scout 0.4.46`, which no longer holds click below 8.4). In click 8.4, `types.py` declares:

```python
ParamTypeValue = t.TypeVar("ParamTypeValue")

class ParamType(t.Generic[ParamTypeValue], abc.ABC):
    ...
    def convert(self, value: t.Any, param: Parameter | None, ctx: Context | None) -> ParamTypeValue: ...
```

`pyproject.toml:147` sets `disallow_any_generics = true` for the `inspect_ai.*` override, so subclassing the now-generic `ParamType` without a type argument is an error.

The two spellings are mutually exclusive across the supported click range, which is why this has flip-flopped:

* **`class _IntOrClearType(click.ParamType[int | Literal["clear"]])`** (the `TYPE_CHECKING` alias form introduced in #4954) — fine on click >= 8.4, but on click < 8.4 mypy reports `"ParamType" expects no type arguments, but 1 given  [type-arg]`, and the subscript raises `TypeError: type 'ParamType' is not subscriptable` at runtime.
* **`class _IntOrClearType(click.ParamType)`** (the current form, adopted in 6fb3265a2 / #4985 precisely because CI was then resolving an older click) — fine on click < 8.4, but trips `disallow_any_generics` on click >= 8.4. That is this failure.

So the fix has to be version-agnostic rather than picking a side. Conveniently both errors carry the same `type-arg` code, and the `inspect_ai.*` override already sets `disable_error_code = "unused-ignore"` (`pyproject.toml:154`) — so a single `# type: ignore[type-arg]` suppresses the error on whichever click is resolved and is silently inert on the other.

### Verification

Reproduced and fixed outside CI with mypy 2.3.1 and the repo's `inspect_ai.*` option set, against a minimal module carrying the same class definition:

| click | current code | with `# type: ignore[type-arg]` |
| --- | --- | --- |
| 8.4.0 | `error: Missing type arguments for generic type "ParamType"  [type-arg]` (byte-identical to CI) | clean |
| 8.1.8 | clean | clean |

Also confirmed the suppression mechanism is real and not accidental: with `disable_error_code = "unused-ignore"` removed from the override, click 8.1.8 reports `Unused "type: ignore" comment  [unused-ignore]` — i.e. the existing override is exactly what makes the one-liner version-agnostic. (Caveat: validated on a faithful minimal repro of the class, not a full-repo mypy run, since the complete dependency set isn't installable in the triage environment.)

## Proposed fix

One line: keep the unparametrized base and suppress `type-arg`, replacing the now-stale comment. Apply to `inspect_ai/src/inspect_ai/_cli/ctl/_group.py`:

```diff
--- a/src/inspect_ai/_cli/ctl/_group.py
+++ b/src/inspect_ai/_cli/ctl/_group.py
@@ -21,11 +21,13 @@ from ._failure import _fail
 from ._render import _echo
 
 
-# click 8.4 made ParamType generic in its stubs, but the package supports
-# older click (>=8.1.3) whose stubs reject the subscript (and CI can resolve
-# such versions, e.g. via inspect-scout's click pin), so subclass the
-# unparametrized base; convert() carries the concrete return type.
-class _IntOrClearType(click.ParamType):
+# click 8.4 made ParamType generic; the older click the package still supports
+# (>=8.1.3) did not, and each spelling errors under the other version - the
+# bare base trips disallow_any_generics on >=8.4, the subscript is rejected on
+# <8.4. Both are `type-arg`, so ignore it here; the pyproject `inspect_ai.*`
+# override disables `unused-ignore`, so the comment is inert on the version
+# that needs no suppression. convert() carries the concrete return type.
+class _IntOrClearType(click.ParamType):  # type: ignore[type-arg]
     """Non-negative integer, or the keyword ``clear`` (restore launch config).
 
     The override knobs' value domain (the retry overrides and the per-sample
```

There is precedent for exactly this shape in the repo — `src/inspect_ai/analysis/_prepare/log_viewer.py` and `task_info.py` carry `# type: ignore[type-arg]` on `pd.Series` sites.

Notes for the implementer:

* Do **not** pin click away from 8.4 in `requirements.txt`. click 8.4.2 is fine at runtime (both slow-test legs passed against it); the exclusions there are for genuine runtime regressions.
* No CHANGELOG entry — this is a typing/CI-only change with no user-facing behavior change.
* Verified alternative, if a reviewer prefers keeping the precise type parameter: restore the `TYPE_CHECKING` alias from #4954 with an ignore on the subscript line (`_IntOrClearBase = click.ParamType[int | Literal["clear"]]  # type: ignore[type-arg]`, `else: _IntOrClearBase = click.ParamType`). That also checks clean on both 8.1.8 and 8.4.0, but it is ~8 lines instead of 1 and buys little here, since `convert()` already declares the concrete return type and `_INT_OR_CLEAR` is only ever handed to `click.option(type=...)`. The one-liner above is the recommended change.

## Suggested follow-up

This issue carries the `auto` label, so the autonomous agent will implement the proposed fix and open a PR into the automated review loop. If that doesn't engage (or the fix needs rework), a PR can be created manually:

```
cd <path-to-inspect_ai-clone>
git checkout -b claude/triage-32491036641
claude "Read issue #306 in meridianlabs-ai/inspect_ai and open a PR
        against UKGovernmentBEIS/inspect_ai main that implements the
        proposed fix."
```

## Links

- Failed run: https://github.com/meridianlabs-ai/actions/actions/runs/32491036641
- Triage run: https://github.com/meridianlabs-ai/actions/actions/runs/32492803843
- Tested commit: https://github.com/UKGovernmentBEIS/inspect_ai/commit/3f294e61b823d6bad5fc16706fc5825ea980c8ee (`origin/main` has 0 commits past it)
- Commit that adopted the currently-failing spelling: https://github.com/UKGovernmentBEIS/inspect_ai/commit/6fb3265a2

**Comment by i-am-marvin** [comment]
**Claude finished @i-am-marvin's task in 6m 58s** —— [View job](https://github.com/meridianlabs-ai/inspect_ai/actions/runs/32493399397) • [`claude/issue-306-20260821-1441`](https://github.com/meridianlabs-ai/inspect_ai/tree/claude/issue-306-20260821-1441) • [Create PR ➔](https://github.com/meridianlabs-ai/inspect_ai/compare/main...claude/issue-306-20260821-1441?quick_pull=1&title=Issue%20%23306%3A%20Changes%20from%20Claude&body=This%20PR%20addresses%20issue%20%23306%0A%0AGenerated%20with%20%5BClaude%20Code%5D(https%3A%2F%2Fclaude.ai%2Fcode)

---
Implemented the proposed fix and opened draft PR [#307](https://github.com/meridianlabs-ai/inspect_ai/pull/307).

### Todo
- [x] Read issue and understand the request
- [x] Read `src/inspect_ai/_cli/ctl/_group.py`
- [x] Apply the `# type: ignore[type-arg]` fix with updated comment
- [x] Install project and run ruff + mypy on the changed file
- [x] Run a fresh-context review pass
- [x] Commit, push, and open a draft PR

### Summary

Applied the one-liner exactly as proposed in the issue: kept the unparametrized `click.ParamType` base in `src/inspect_ai/_cli/ctl/_group.py` and added `# type: ignore[type-arg]`, replacing the stale comment with one explaining why this spelling is version-agnostic (both failure modes are `type-arg`, and the `inspect_ai.*` mypy override's `disable_error_code = "unused-ignore"` makes the comment inert on the click version that needs no suppression).

**Verification** (project installed with `pip install -e ".[dev]"`):
- `mypy src/inspect_ai/_cli/ctl/_group.py` — clean with **click 8.1.6** (no unused-ignore warning) and clean with **click 8.4.2** (error suppressed), confirming both sides of the supported range.
- `ruff check` and `ruff format --check` on the changed file — pass.
- A fresh-context review pass (Claude Fable 5 subagent) found no defects; it also confirmed this is the only `ParamType` subclass in the repo and that the ignore is narrow enough to not mask other errors.

Per the issue's notes: click was **not** pinned away from 8.4, and no CHANGELOG entry was added (typing/CI-only change).
 · [Branch](https://github.com/meridianlabs-ai/inspect_ai/tree/claude/issue-306-20260821-1441)

**Comment by ransomr** [comment]
Fixed upstream independently: UKGovernmentBEIS/inspect_ai#4992 (merged 2026-08-21). Fork PR #307 was closed as a duplicate — closing this issue with it.
